const EXERCISES = [
    { type: 'Грамматика', q: 'Ҷумлаи дурустро интихоб кунед.', o: ['Ман китобро мехонад.', 'Ман китобро мехонам.', 'Ман китобро хондан.'], c: 1 },
    { type: 'Грамматика', q: 'Дар ҷумлаи «Донишҷӯи фаъол хуб мехонад» калимаи «фаъол» кадом ҳиссаи нутқ аст?', o: ['Исм', 'Сифат', 'Феъл', 'Зарф'], c: 1 },
    { type: 'Грамматика', q: 'Шакли дурусти феъли ояндаро интихоб кунед: «Ӯ пагоҳ ба дарс ...».', o: ['омад', 'меояд', 'хоҳад омад', 'омадааст'], c: 2 },
    { type: 'Грамматика', q: 'Кадом ҷумла мураккаб аст?', o: ['Баҳор омад.', 'Офтоб баромад ва ҳаво гарм шуд.', 'Кӯдакон хурсанданд.'], c: 1 },
    { type: 'Грамматика', q: 'Пешоянди дуруст: «Китоб ... рӯйи миз аст».', o: ['ба', 'аз', 'дар', 'бо'], c: 2 },
    { type: 'Грамматика', q: 'Кадом калима ҷонишин аст?', o: ['ман', 'зебо', 'хондан', 'имрӯз'], c: 0 },
    { type: 'Грамматика', q: 'Шакли дурустро интихоб кунед: «Духтарон ...».', o: ['меомад', 'меоянд', 'меояд', 'омадан'], c: 1 },
    { type: 'Грамматика', q: 'Дар ҷумлаи «Вай ором сухан гуфт» калимаи «ором» чӣ вазифа дорад?', o: ['Зарф', 'Исм', 'Ҷонишин', 'Пайвандак'], c: 0 },
    { type: 'Луғат · синоним', q: 'Синоними калимаи «зебо»-ро интихоб кунед.', o: ['зишт', 'хушрӯ', 'баланд', 'дур'], c: 1 },
    { type: 'Луғат · антоним', q: 'Антоними калимаи «оғоз» кадом аст?', o: ['ибтидо', 'анҷом', 'марказ', 'роҳ'], c: 1 },
    { type: 'Луғат · контекст', q: 'Дар ҷумлаи «Ӯ дили бузург дорад» калимаи «бузург» чӣ маъно дорад?', o: ['қадбаланд', 'меҳрубон ва саховатманд', 'пир', 'дур'], c: 1 },
    { type: 'Луғат · синоним', q: 'Синоними «ҷасур» кадом аст?', o: ['далер', 'танбал', 'ором', 'хомӯш'], c: 0 },
    { type: 'Имло', q: 'Навишти дурустро интихоб кунед.', o: ['муаллим', 'муаллимм', 'муалим', 'муалимм'], c: 0 },
    { type: 'Имло', q: 'Кадом калима дуруст навишта шудааст?', o: ['масъала', 'масала', 'масьала', 'масъалаь'], c: 0 },
    { type: 'Имло', q: 'Навишти дурусти калимаро ёбед.', o: ['рӯзномa', 'рӯзнома', 'рузнома', 'рӯзномаӣ'], c: 1 },
    { type: 'Имло', q: 'Кадом шакл дуруст аст?', o: ['меҳмонхона', 'мехмонхона', 'меҳмон хонаи', 'меҳмонҳона'], c: 0 },
    { type: 'Имло', q: 'Калимаи дурустро интихоб кунед.', o: ['таърих', 'таърех', 'тарих', 'таърихъ'], c: 0 },
    { type: 'Имло', q: 'Номи хосро чӣ гуна менависем?', o: ['душанбе', 'Душанбе', 'ДУШАНБЕ танҳо', 'душанбеӣ'], c: 1 },
    { type: 'Ибора', q: 'Маънои ибораи «сар ба осмон расидан» чист?', o: ['баланд паридан', 'хеле хурсанд шудан', 'хоб рафтан', 'сафар кардан'], c: 1 },
    { type: 'Мақол', q: 'Мақоли «Як даст садо надорад» ба кадом маъно наздик аст?', o: ['Корро танҳо кардан беҳтар аст.', 'Ҳамкорӣ қувват мебахшад.', 'Даст узви бадан аст.', 'Садо муҳим нест.'], c: 1 },
    { type: 'Мақол', q: 'Идомаи дурусти мақолро интихоб кунед: «Ҳар чӣ корӣ,...»', o: ['ҳамон мехонӣ', 'ҳамон даравӣ', 'ҳамон медонӣ', 'ҳамон менависӣ'], c: 1 },
    { type: 'Адабиёт', q: 'Асари «Шоҳнома» ба кадом шоир тааллуқ дорад?', o: ['Рӯдакӣ', 'Фирдавсӣ', 'Саъдӣ', 'Айнӣ'], c: 1 },
    { type: 'Адабиёт', q: '«Гулистон» асари кадом адиб аст?', o: ['Саъдӣ', 'Ҳофиз', 'Турсунзода', 'Фирдавсӣ'], c: 0 },
    { type: 'Хониш', q: 'Матн: «Об барои саломатӣ муҳим аст. Он ба кори дурусти бадан ёрӣ медиҳад.» Ғояи асосӣ чист?', o: ['Об танҳо барои варзиш аст.', 'Об барои саломатӣ зарур аст.', 'Бадан бе об ҳам кор мекунад.', 'Варзиш аз об муҳимтар аст.'], c: 1 }
];
let exerciseIndex = 0, exerciseScore = 0, exerciseAnswered = false;
function renderExercise() { const e = EXERCISES[exerciseIndex]; document.getElementById('exercise-count').textContent = `Машқ ${exerciseIndex + 1} аз ${EXERCISES.length}`; document.getElementById('exercise-type').textContent = e.type; document.getElementById('exercise-question').textContent = e.q; document.getElementById('exercise-feedback').textContent = ''; document.getElementById('exercise-feedback').className = 'feedback'; document.getElementById('check-button').classList.remove('hidden'); document.getElementById('next-button').classList.add('hidden'); exerciseAnswered = false; document.getElementById('exercise-options').innerHTML = e.o.map((option, index) => `<button class="option-button" type="button" data-option="${index}">${option}</button>`).join(''); document.querySelectorAll('#exercise-options .option-button').forEach(button => button.addEventListener('click', () => { if (!exerciseAnswered) { document.querySelectorAll('#exercise-options .option-button').forEach(item => item.classList.remove('selected')); button.classList.add('selected') } })) }
function checkExercise() { const selected = document.querySelector('#exercise-options .selected'), feedback = document.getElementById('exercise-feedback'); if (!selected) { feedback.textContent = 'Аввал як ҷавобро интихоб кунед.'; feedback.className = 'feedback error'; return } exerciseAnswered = true; const correct = Number(selected.dataset.option) === EXERCISES[exerciseIndex].c; document.querySelectorAll('#exercise-options .option-button').forEach((button, index) => { button.disabled = true; if (index === EXERCISES[exerciseIndex].c) button.classList.add('correct'); else if (button === selected) button.classList.add('wrong') }); if (correct) { exerciseScore++; feedback.textContent = 'Дуруст!'; feedback.className = 'feedback success' } else { feedback.textContent = `Нодуруст. Ҷавоби дуруст: ${EXERCISES[exerciseIndex].o[EXERCISES[exerciseIndex].c]}`; feedback.className = 'feedback error' } document.getElementById('check-button').classList.add('hidden'); document.getElementById('next-button').classList.remove('hidden') }
function nextExercise() { if (exerciseIndex < EXERCISES.length - 1) { exerciseIndex++; renderExercise() } else { document.getElementById('exercise-options').innerHTML = ''; document.getElementById('exercise-question').textContent = 'Машқҳо ба анҷом расиданд.'; document.getElementById('exercise-feedback').textContent = ''; document.getElementById('check-button').classList.add('hidden'); document.getElementById('next-button').classList.add('hidden'); const result = document.getElementById('practice-result'); result.classList.remove('hidden'); result.innerHTML = `<h2>Натиҷаи машқ</h2><span class="result-score">${exerciseScore} / ${EXERCISES.length}</span><p class="result-detail">Шумо ${Math.round(exerciseScore / EXERCISES.length * 100)}% ҷавобҳоро дуруст интихоб кардед.</p>` } }
document.addEventListener('DOMContentLoaded', () => { if (document.getElementById('exercise-question')) { renderExercise(); document.getElementById('check-button').addEventListener('click', checkExercise); document.getElementById('next-button').addEventListener('click', nextExercise) } });